# Generated by Django 5.2.6 on 2026-05-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyectos', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=100)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='proyectos/portadas/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('TERMINADO', 'Terminado'), ('ESCRITURACION', 'Escrituracion')], default='ACTIVO', max_length=20)),
                ('cant_viviendas', models.IntegerField(default=0)),
                ('m2_zona_verde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('m2_urbanismo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numero_pisos', models.IntegerField(default=0)),
                ('numero_bloques', models.IntegerField(default=0)),
                ('sistema_constructivo', models.CharField(max_length=100)),
                ('link_planos', models.URLField(max_length=500)),
                ('cant_empleados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
    ]
