# Generated by Django 5.2.6 on 2025-10-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('personal', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('tipo_registro', models.CharField(choices=[('manual', 'Registro manual'), ('seleccion', 'Registro por selección')], default='manual', max_length=20)),
                ('rol', models.CharField(choices=[('global', 'Superusuario global'), ('area', 'Superusuario de área'), ('normal', 'Usuario normal')], default='normal', max_length=20, verbose_name='Rol del usuario')),
                ('nombre_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area_asignada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área o módulo asignado')),
                ('permisos', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='personal.empleado')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='usuario_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuario_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Funcionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100, verbose_name='Módulo o área del sistema')),
                ('submodulo', models.CharField(max_length=100, verbose_name='Subárea o vista')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la funcionalidad')),
                ('acciones', models.JSONField(default=list, verbose_name='Acciones disponibles (crear, ver, etc.)')),
            ],
            options={
                'verbose_name': 'Funcionalidad',
                'verbose_name_plural': 'Funcionalidades',
                'db_table': 'funcionalidades',
                'unique_together': {('app', 'submodulo')},
            },
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acciones_permitidas', models.JSONField(default=list, verbose_name='Acciones permitidas (ver, crear, editar, eliminar)')),
                ('puede_asignar', models.BooleanField(default=False, verbose_name='¿Puede asignar estos permisos a otros usuarios?')),
                ('funcionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='usuario.funcionalidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
                'db_table': 'permisos_usuario',
                'unique_together': {('usuario', 'funcionalidad')},
            },
        ),
    ]
