# Generated by Django 5.2.6 on 2025-10-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionalidad',
            name='descripcion',
        ),
    ]
