# Generated by Django 5.2.6 on 2025-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_funcionalidad_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='funcionalidad',
            name='submodulo',
            field=models.CharField(max_length=200, verbose_name='Subárea o vista'),
        ),
    ]
