# Generated by Django 5.2.6 on 2025-10-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0005_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('global', 'Superusuario'), ('area', 'Encargado de área'), ('normal', 'Usuario normal')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_asignada',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Área o módulo asignado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_permissions', to='auth.permission'),
        ),
    ]
