# Generated by Django 5.2.6 on 2025-10-22 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_remove_usuario_activo_remove_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionalidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permisousuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='funcionalidad',
            name='acciones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='funcionalidad',
            name='app',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionalidad',
            name='submodulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='acciones_permitidas',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='funcionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.funcionalidad'),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='puede_asignar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permisousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_asignada',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
