# Generated by Django 5.2.6 on 2025-11-27 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0005_empleado_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cumplimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('u', 'u'), ('m³', 'm³'), ('m²', 'm²'), ('m', 'm'), ('kg', 'kg')], default='u', max_length=100)),
                ('cumplimiento_presupuestal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cumplimiento_programado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Cumplimiento',
                'verbose_name_plural': 'Cumplimientos',
                'db_table': 'cumplimientos',
            },
        ),
        migrations.CreateModel(
            name='MedicionCuadrilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proyecto', models.CharField(choices=[('Ciudadela Andina', 'Ciudadela Andina')], default='Ciudadela Andina', max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cuadrilla', models.CharField(max_length=100, verbose_name='Número de cuadrilla')),
                ('numero_oficiales_ayudantes', models.CharField(blank=True, max_length=100, null=True)),
                ('empleado_cedula', models.CharField(blank=True, help_text='Cédulas de los empleados al momento del registro (para trazabilidad)', max_length=500, null=True)),
                ('nombre_empleado', models.CharField(blank=True, help_text='Nombre del empleado al momento del registro (para trazabilidad)', max_length=500, null=True)),
                ('usuario_cedula', models.CharField(blank=True, help_text='Cédula del usuario que registró la medición', max_length=500, null=True)),
                ('nombre_usuario', models.CharField(blank=True, help_text='Nombre del usuario que registró la medición', max_length=500, null=True)),
                ('precio_hora_trabajadores', models.CharField(blank=True, help_text='Precio hora trabajadores al momento del registro (para trazabilidad)', max_length=500, null=True)),
                ('actividad', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_inicio_empleados', models.CharField(blank=True, help_text='Horas de inicio granular por empleado ', max_length=2000, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('horas_efectivas_trabajador', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horas_trabajadas_totales', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('costo_total_oficiales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_total_ayudantes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_total_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_producida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rendimiento_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comparacion_presupuestal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comparacion_programado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('costo_por_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empleados', models.ManyToManyField(blank=True, related_name='mediciones', to='personal.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición de Cuadrilla',
                'verbose_name_plural': 'Mediciones de Cuadrilla',
                'db_table': 'mediciones_cuadrilla',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambiosCuadrilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_salida', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_entrada', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('desayuno', models.BooleanField(default=False)),
                ('almuerzo', models.BooleanField(default=False)),
                ('cedula_usuario', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=500, null=True)),
                ('quien_entro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_historial', to='personal.empleado')),
                ('quien_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_historial', to='personal.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='medicion_rendimiento.medicioncuadrilla')),
            ],
            options={
                'db_table': 'historial_cambios_cuadrilla',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
