# Generated by Django 5.2.6 on 2025-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='almuerzo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='desayuno',
            field=models.BooleanField(default=False),
        ),
    ]
