# Generated by Django 5.2.6 on 2025-12-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0002_medicioncuadrilla_almuerzo_and_more'),
        ('personal', '0005_empleado_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desayuno', models.BooleanField(default=False)),
                ('almuerzo', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_alimento', to='personal.empleado')),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='medicion_rendimiento.medicioncuadrilla')),
            ],
            options={
                'unique_together': {('medicion', 'empleado')},
            },
        ),
    ]
