# Generated by Django 5.2.6 on 2025-12-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0003_consumoalimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicioncuadrilla',
            name='almuerzo',
        ),
        migrations.RemoveField(
            model_name='medicioncuadrilla',
            name='desayuno',
        ),
    ]
