# Generated by Django 5.2.6 on 2025-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0004_remove_medicioncuadrilla_almuerzo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='hora_fin_empleados',
            field=models.CharField(blank=True, help_text='Horas de fin granular por empleado ', max_length=2000, null=True),
        ),
    ]
