# Generated by Django 5.2.6 on 2025-12-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0005_medicioncuadrilla_hora_fin_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicioncuadrilla',
            name='horas_efectivas_trabajador',
            field=models.CharField(blank=True, help_text='Horas efectivas por trabajador ', max_length=2000, null=True),
        ),
    ]
