# Generated by Django 5.2.6 on 2025-12-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0006_alter_medicioncuadrilla_horas_efectivas_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcambioscuadrilla',
            name='almuerzo',
        ),
        migrations.RemoveField(
            model_name='historialcambioscuadrilla',
            name='desayuno',
        ),
    ]
