# Generated by Django 5.2.6 on 2025-12-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0007_remove_historialcambioscuadrilla_almuerzo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='cumplimiento_presupuestal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='cumplimiento_programado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
