# Generated by Django 5.2.6 on 2025-12-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0008_medicioncuadrilla_cumplimiento_presupuestal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicioncuadrilla',
            name='cantidad_producida',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
