# Generated by Django 5.2.6 on 2025-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0010_alter_medicioncuadrilla_cumplimiento_presupuestal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumplimiento',
            name='cumplimiento_presupuestal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
