# Generated by Django 5.2.6 on 2025-12-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0011_alter_cumplimiento_cumplimiento_presupuestal'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='foto_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='mediciones/inicio/'),
        ),
    ]
