# Generated by Django 5.2.6 on 2026-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0012_medicioncuadrilla_foto_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicioncuadrilla',
            name='comparacion_presupuestal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
