# Generated by Django 5.2.6 on 2026-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0013_alter_medicioncuadrilla_comparacion_presupuestal'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='diferencia_presupuestal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
