# Generated by Django 5.2.6 on 2026-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0014_medicioncuadrilla_diferencia_presupuestal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicioncuadrilla',
            name='comparacion_programado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='medicioncuadrilla',
            name='diferencia_presupuestal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
