# Generated by Django 5.2.6 on 2026-01-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0015_alter_medicioncuadrilla_comparacion_programado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncuadrilla',
            name='foto_fin',
            field=models.ImageField(blank=True, null=True, upload_to='mediciones/fin/'),
        ),
    ]
