# Generated by Django 5.2.6 on 2026-01-28 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0016_medicioncuadrilla_foto_fin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('CIERRE_DIARIO', 'Cierre Diario (5:00 PM)')], default='CIERRE_DIARIO', max_length=50, unique=True)),
                ('destinatarios', models.ManyToManyField(help_text='Seleccione los usuarios que recibirán esta alerta', related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Alerta',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
    ]
