# Generated by Django 5.2.6 on 2026-01-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0017_configuracionalerta'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracionalerta',
            table='configuraciones_alertas',
        ),
    ]
