# Generated by Django 5.2.6 on 2026-01-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0018_alter_configuracionalerta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalerta',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo del usuario que configuró la alerta', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracionalerta',
            name='nombre_usuario',
            field=models.CharField(blank=True, help_text='Nombre del usuario que configuró la alerta', max_length=500, null=True),
        ),
    ]
