# Generated by Django 5.2.6 on 2026-01-28 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0019_configuracionalerta_correo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionalerta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_alertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuracionalerta',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
