# Generated by Django 5.2.6 on 2026-01-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0020_configuracionalerta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalerta',
            name='correo',
            field=models.CharField(blank=True, help_text='Correo del usuario que configuró la alerta', max_length=500, null=True),
        ),
    ]
