# Generated by Django 5.2.6 on 2026-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0021_alter_configuracionalerta_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('CIERRE_DIARIO', 'Cierre Diario (5:00 PM)')], default='CIERRE_DIARIO', max_length=50),
        ),
    ]
