# Generated by Django 5.2.6 on 2026-01-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0022_alter_configuracionalerta_tipo_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('CIERRE_DIARIO', 'Cierre Diario (5:00 PM)'), ('ELIMINAR', 'Eliminar')], default='CIERRE_DIARIO', max_length=50),
        ),
    ]
