# Generated by Django 5.2.6 on 2026-01-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0023_alter_configuracionalerta_tipo_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionalerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('Cierre diario', 'Cierre Diario (5:00 PM)')], default='CIERRE_DIARIO', max_length=50),
        ),
    ]
