# Generated by Django 5.2.6 on 2026-06-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0024_alter_configuracionalerta_tipo_alerta'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicioncuadrilla',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_rendimiento', to='proyectos.proyecto'),
        ),
    ]
