# Generated by Django 5.2.6 on 2026-06-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion_rendimiento', '0025_alter_medicioncuadrilla_proyecto'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumplimiento',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='cumplimiento',
            name='actividad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cumplimiento',
            name='cumplimiento_presupuestal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cumplimiento',
            name='cumplimiento_programado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cumplimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cumplimiento',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
