# Generated by Django 5.2.6 on 2025-10-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
    ]
