# Generated by Django 5.2.6 on 2025-11-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_empleado_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='costo',
        ),
    ]
