# Generated by Django 5.2.6 on 2025-11-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_empleado_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
