# Generated by Django 5.2.6 on 2025-12-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_empleado_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='costo',
        ),
    ]
