# Generated by Django 5.2.6 on 2025-12-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_remove_empleado_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ayudante_raso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
