# Generated by Django 5.2.6 on 2025-12-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_empleado_ayudante_raso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ayudante_entendido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='oficial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
