# Generated by Django 5.2.6 on 2025-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_empleado_ayudante_entendido_empleado_oficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayudante_raso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ayudante_entendido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oficial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Valor Hora',
                'verbose_name_plural': 'Valores Hora',
                'db_table': 'valores_hora',
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ayudante_entendido',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ayudante_raso',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='oficial',
        ),
    ]
