# Generated by Django 5.2.6 on 2026-01-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_valorhora_remove_empleado_ayudante_entendido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorhora',
            old_name='ayudante_raso',
            new_name='ayudante',
        ),
        migrations.RenameField(
            model_name='valorhora',
            old_name='oficial',
            new_name='oficial_junior',
        ),
        migrations.AddField(
            model_name='valorhora',
            name='oficial_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
