# Generated by Django 5.2.6 on 2026-01-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_rename_ayudante_raso_valorhora_ayudante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorhora',
            name='oficial_senior',
        ),
    ]
