# Generated by Django 5.2.6 on 2026-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_remove_valorhora_oficial_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorhora',
            name='oficial_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
