# Generated by Django 5.2.6 on 2026-01-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_valorhora_oficial_senior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorhora',
            old_name='ayudante',
            new_name='ayudante_raso',
        ),
    ]
