# Generated by Django 5.2.6 on 2026-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_rename_ayudante_valorhora_ayudante_raso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValorHora',
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
