# Generated by Django 5.2.6 on 2026-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_delete_valorhora_empleado_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
