# Generated by Django 5.2.6 on 2026-06-01 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('clima_manana', models.CharField(blank=True, max_length=20, null=True)),
                ('clima_tarde', models.CharField(blank=True, max_length=20, null=True)),
                ('equipo_obra', models.TextField(blank=True, null=True)),
                ('actividades', models.TextField(blank=True, null=True)),
                ('cant_maestros', models.IntegerField(default=0)),
                ('cant_oficiales', models.IntegerField(default=0)),
                ('cant_ayudantes', models.IntegerField(default=0)),
                ('cant_contratistas', models.IntegerField(default=0)),
                ('firma_autor_url', models.ImageField(blank=True, null=True, upload_to='bitacoras/firmas/')),
                ('firma_supervisor_url', models.ImageField(blank=True, null=True, upload_to='bitacoras/firmas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_autor', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='proyectos.proyecto')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraFoto',
            fields=[
                ('id_bitacora_fotos', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.ImageField(upload_to='bitacoras/fotos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='bitacora.bitacora')),
            ],
            options={
                'db_table': 'bitacora_fotos',
            },
        ),
    ]
